# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Run echo command
          command: echo 'hello'
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Run echo command
          command: echo 'world'
      - run:
          name: Print developers name
          command: echo ${DEV_NAME}
workflows:
  example:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
